# Generated by Django 3.0.1 on 2020-04-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functionName', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('defType', models.CharField(max_length=50)),
                ('isTested', models.BooleanField(default=False)),
            ],
        ),
    ]
